# Generated by Django 5.0 on 2023-12-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='create',
            new_name='created',
        ),
    ]
