# Generated by Django 5.0 on 2023-12-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_cliente_options_rename_create_cliente_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'clientes', 'verbose_name_plural': 'clientes'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='costo',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codigo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
